### ISSUE TITLE
dor-02 breaks the pipeline

### ISSUE THREAD

**Issue by TheSkyentist** [OutThere-JWST/NISPureParallel#14]
When running contamination modeling, we get the following error:
> Traceback (most recent call last):
>   File "/vera/ptmp/gc/rahvi/NISPureParallel/./workflow/scripts/contamination.py", line 198, in <module>
>     main()
>   File "/vera/ptmp/gc/rahvi/NISPureParallel/./workflow/scripts/contamination.py", line 90, in main
>     grp = auto_script.grism_prep(
>           ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/vera/ptmp/gc/rahvi/NISPureParallel/.snakemake/conda/048bc6b3a64f4c0b500a7ffe7954d6e9_/lib/python3.12/site-packages/grizli/pipeline/auto_script.py", line 3541, in grism_prep
>     n = scipy.stats.norm.fit(clip_data)
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/vera/ptmp/gc/rahvi/NISPureParallel/.snakemake/conda/048bc6b3a64f4c0b500a7ffe7954d6e9_/lib/python3.12/site-packages/scipy/stats/_continuous_distns.py", line 74, in wrapper
>     return fun(self, data, *args, **kwds)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/vera/ptmp/gc/rahvi/NISPureParallel/.snakemake/conda/048bc6b3a64f4c0b500a7ffe7954d6e9_/lib/python3.12/site-packages/scipy/stats/_continuous_distns.py", line 416, in fit
>     raise ValueError("The data contains non-finite values.")
> ValueError: The data contains non-finite values.

**Comment by TheSkyentist** [comment]
Appears to be related to the GR150R grism only?

**Comment by TheSkyentist** [comment]
We are now getting this error:

>   File "/vera/ptmp/gc/rahvi/NISPureParallel/./workflow/scripts/contamination.py", line 198, in <module>
>     main()
>   File "/vera/ptmp/gc/rahvi/NISPureParallel/./workflow/scripts/contamination.py", line 109, in main
>     grp.drizzle_grism_models(
>   File "/vera/ptmp/gc/rahvi/NISPureParallel/.snakemake/conda/048bc6b3a64f4c0b500a7ffe7954d6e9_/lib/python3.12/site-packages/grizli/multifit.py", line 1108, in drizzle_grism_models
>     xmi = np.maximum(xp[mask].min()-10, 0)
>                      ^^^^^^^^^^^^^^
>   File "/vera/ptmp/gc/rahvi/NISPureParallel/.snakemake/conda/048bc6b3a64f4c0b500a7ffe7954d6e9_/lib/python3.12/site-packages/numpy/core/_methods.py", line 45, in _amin
>     return umr_minimum(a, axis, None, out, keepdims, initial, where)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ValueError: zero-size array to reduction operation minimum which has no identity

**Comment by TheSkyentist** [comment]
This appears to be due to pre-processing, where only the R grisms drizzles are completely set to zero everywhere

**Comment by TheSkyentist** [comment]
This might also be related to #1

**Comment by TheSkyentist** [comment]
It just seemed to start working...? It will be worth checking the output.
